### ISSUE TITLE
Unquoted strings in Sass maps

### ISSUE THREAD

**Issue by ArmorDarks** [MathiasPaumgarten/grunt-shared-config#25]
Hi

First of all, thanks for great product!

It seems that Sass maps generation has some issues due to lack of quotes.

For example, following generated Sass map will through an error:

``` sass
$grunt-data: (
	site: (
		lang: en,
		name: Kotsu,
		title: Clean, opinionated foundation for new projects — to boldly go where no man has gone before,
		version: 0.5.3
	)
);
```

```
Error: Invalid CSS after "...has gone before": expected ":", was ","
        on line 5 of C:\Working\Kotsu\temp\styles\config.scss
        from line 34 of source/styles/style.scss
```

**Comment by benib** [comment]
I see, this is not handled correctly. `getStyleSafeValue` should probably get more sophisticated. Although I don't see the value of these values in a Sass map.

As a workaround for now: If you enclose the string in the source with `'` or `"`, it should get quoted in the output. If you have JSON data as source, write it like this: `"'Clean, opinionated...'"`.

**Comment by ArmorDarks** [comment]
Hi

Thanks for reply

> Although I don't see the value of these values in a Sass map.

That's true. It's just a content of `package.json`, which we've used for testing, and nobody would pass it to Sass in sane mind. Unless someone wants to pass some text into `content: ' '` property for some reason or make weird things.

Nevertheless, such situation may occure with useful values too. It was just a good opportunity to catch that bug.

> As a workaround for now: If you enclose the string in the source with ' or ", it should get quoted in the output. If you have JSON data as source, write it like this: "'Clean, opinionated...'".

Thanks for your suggestions. If we'll face similar issue with real data — we'll definitely use it :)

**Comment by benib** [comment]
The problem with this string is basically the `,` in it, as it has meaning in the Sass maps syntax.
I never stumbled across a problem with the string handling in grunt-shared-config in real life.
Let us know here if you have one and we will try to fix it.

Are you aware of the masking capabilities of grunt-shared-config? It can help you masking out some values you don't want in the Sass map but happen to be in your config source.

**Comment by robertwbradford** [comment]
I'm running into a similar problem. I'm using this plugin to help create a style guide and need access to certain options both in SCSS and JS. (Great plugin, BTW.) I'm wanting to declare fonts, colors, etc. in my config file but am having a problem when trying to set my font-family properties.

I figured out a workaround and have the following explanation commented in my config source file (`options.yml').
```
# You cannot declare a value in this YAML file like this:
#   font-family: 'Open Sans', sans-serif
# 
# This is because it will be converted to the following in the SCSS map:
#   font-family: 'Open Sans', sans-serif,
# 
# You will then get a SASS error saying:
#   Error: Invalid CSS after "...ns', sans-serif": expected ":", was ","
# 
# This is due to the way SASS handles lists.
# 
# You'll get the same SASS error if you try this in the YAML:
#   font-family: "'Open Sans', sans-serif"
# 
# You could do something like this in the YAML:
#   font-family: "\"'Open Sans', sans-serif\""
# 
# You end up with this in SASS map:
#   font-family: "'Open Sans', sans-serif",
# 
# However is a problem in CSS: 
#   // Doesn't work:
#   font-family: "'Open Sans', sans-serif";
#
#   // Works
#   font-family: 'Open Sans', sans-serif;
# 
# As a workaround, wrap it in parentheses (although it throws off your YAML syntax highlighting):
#   font-family: ('Open Sans', sans-serif)
# 
# This gives you the following in the SASS map:
#   font-family: ('Open Sans', sans-serif),
# 
# When SCSS complies it gives you the correct CSS;
#   font-family: 'Open Sans', sans-serif;
# 
# CAUTION: 
# You also end up with this in your JSON:
#   "font-family": "('Open Sans', sans-serif)",
# 
# You'll have to deal with the parentheses there.
```
Same thing happens when using a JSON source file. Bascially, I'm wanting to end up with proper CSS, but I'm not sure the best to declare everything.

**Comment by benib** [comment]
@robertwbradford thanks for the very detailed explanation of the problem. I hope to find some time in the next days to tackle this.

@MathiasPaumgarten Do you have some other useful testcases for this `getStyleSafeValue` function. If we have to improve it, it would be nice to cover as many cases as possible.

**Comment by MathiasPaumgarten** [comment]
Hey @robertwbradford , thanks for the write up. I also just saw what @tomdavies posted in #28. Very similar issue, mostly concerning that the `,` is an issue in the sass maps. 

I don't know if @tomdavis or @benib are working on this already. I would love to see a PR on this if one of you guys have time. Like @benib has pointed out, I believe this can be solved within the `getStyleSafeValue`.

The issue described in #28 will probably have to be solved seperatly in `generateSassMapsRecursive`. Maybe we have to ass a `mout.lang.isArray` as an addition `else if` as the sass maps require parens around the values, but the CSS safe values should not have one. 

So, one of you guys down to take a stab at a PR. Maybe different ones. 

PS: Sorry that I am so little help on this. Still really slammed. Don't spend enough time on this as I wish I was.

**Comment by tomdavies** [comment]
I'm happy to take a stab at both this and #28 if there are no other takers. Am pretty stacked til the end of the week but will aim to take a shot over the weekend. On Tue, Mar 24, 2015 at 5:11 pm,  MathiasPaumgarten/grunt-shared-config <reply@reply.github.com> wrote:            Hey @robertwbradford , thanks for the write up. I also just saw what @tomdavies posted in #28. Very similar issue, mostly concerning that the , is an issue in the sass maps. 

I don't know if @tomdavis or @benib are working on this already. I would love to see a PR on this if one of you guys have time. Like @benib has pointed out, I believe this can be solved within the getStyleSafeValue.

The issue described in #28 will probably have to be solved seperatly in generateSassMapsRecursive. Maybe we have to ass a mout.lang.isArray as an addition else if as the sass maps require parens around the values, but the CSS safe values should not have one. 

So, one of you guys down to take a stab at a PR. Maybe different ones. 

PS: Sorry that I am so little help on this. Still really slammed. Don't spend enough time on this as I wish I was.

**Comment by benib** [comment]
Just to let you know, I'm not working on this at the moment.

I'd rather not add `if`s to generateSassMapsRecursive but separate `getStyleSafeValue` into different functions per output though.

**Comment by MathiasPaumgarten** [comment]
I agree with @benib. Preferably that. I wasn't 100% sure if that actually covers all cases. The `generateSassMapsRecursive` method is heavy as it is, and could definitely use a refactor.
