### ISSUE TITLE
Namespace variables

### ISSUE THREAD

**Issue by ArmorDarks** [MathiasPaumgarten/grunt-shared-config#26]
Hi

Maybe I've missed it, but for now it seems to be impossible to namespace variable.

It would be great to use `options.name` or additional options value for that purpose, so in result we could get instead of

``` scss
$car-blue: blue;
$car-red: red;
```

namespaced variables, like:

``` scss
$myJSON-car-blue: blue;
$myJSON-car-red: red;
```

**Comment by MathiasPaumgarten** [comment]
This is great input. Maybe we should not use `options.name` as it is already used for the name of the JavaScript object, that it creates when AMD is not used. 

I will put that on my list. It might be a little while until I get around to implementing this. Any chance you are willing to contribute?

**Comment by MathiasPaumgarten** [comment]
This took pretty long, but I finally got around to work on some of my open source projects. This was pretty high on the list. If you grab the latest version of `grunt-shared-config`, now being __`0.3.13`__ you have an additional option `namespace` that can be any string. 
Reference the [README](https://github.com/MathiasPaumgarten/grunt-shared-config#optionsnamespace).

Thanks for contributing to this.

**Comment by ArmorDarks** [comment]
Sounds great! Thanks a lot for your hard work!

> Thanks for contributing to this.

I really wished that I could indeed contribute, but I'm not familiar with Node enough. Yet.
