### ISSUE TITLE
Extend to support wildcard src / dest

### ISSUE THREAD

**Issue by AtiX** [MathiasPaumgarten/grunt-shared-config#32]
I think it would be great to be able to specify wildcards in source/destination:

```
src: "config/*.yml",
   dest: [
      "styles/config/*.sass",
      "scripts/config/*.json"
   ]
```

The expected behaviour would be that for each `yml` file, a `sass` and `json` file (with the same name) would be created as well.

What do you think?

**Comment by roboshoes** [comment]
Hey there, thanks for the input. I haven't worked on this plugin in a while. I believe it works with the built in globbing expansion of grunt so far. I have to look into expanding it to this. 

I appreciate the feedback!

**Comment by AtiX** [comment]
You're right - I played around with it and at least input wildcards give good results when exporting for one destination file type (e.g. `json` in this case):

```
files: [{
  src: 'config/*.yml'
  dest: 'config/'
  expand: true
  ext: '.json'
}]
```

Unfortunately you have to repeat this config for each extension, since the ext field does not seem to support patterns - at least what I tried. But I guess this is more a grunt issue than an issue of this plugin.

**Comment by roboshoes** [comment]
Thanks for the update. I'd rather not move away from the built-in globbbing system from Grunt for a whole slur of reasons. If you can make it work somehow like this, all the better. 
👍  Happy Coding!!
